//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetisTest.SWRecuperarContrasena {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioSOAT.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWRecuperarContrasena.IRecuperarContrasena")]
    public interface IRecuperarContrasena {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperarContrasena/RecuperarContrasenaUsuario", ReplyAction="http://tempuri.org/IRecuperarContrasena/RecuperarContrasenaUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NetisTest.SWRecuperarContrasena.RepetidoException), Action="http://tempuri.org/IRecuperarContrasena/RecuperarContrasenaUsuarioRepetidoExcepti" +
            "onFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/WCFServicioSOAT.Errores")]
        string RecuperarContrasenaUsuario(string stCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecuperarContrasena/RecuperarContrasenaUsuario", ReplyAction="http://tempuri.org/IRecuperarContrasena/RecuperarContrasenaUsuarioResponse")]
        System.Threading.Tasks.Task<string> RecuperarContrasenaUsuarioAsync(string stCorreo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRecuperarContrasenaChannel : NetisTest.SWRecuperarContrasena.IRecuperarContrasena, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecuperarContrasenaClient : System.ServiceModel.ClientBase<NetisTest.SWRecuperarContrasena.IRecuperarContrasena>, NetisTest.SWRecuperarContrasena.IRecuperarContrasena {
        
        public RecuperarContrasenaClient() {
        }
        
        public RecuperarContrasenaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecuperarContrasenaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperarContrasenaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperarContrasenaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RecuperarContrasenaUsuario(string stCorreo) {
            return base.Channel.RecuperarContrasenaUsuario(stCorreo);
        }
        
        public System.Threading.Tasks.Task<string> RecuperarContrasenaUsuarioAsync(string stCorreo) {
            return base.Channel.RecuperarContrasenaUsuarioAsync(stCorreo);
        }
    }
}
